#!/bin/bash
set -o errexit -o nounset -o pipefail

function query {
  ./sql -XqAt -c "SELECT $1"
}

function check {
  local n="$RANDOM"
  data="$(query "$n")"
  set -x
  [[ $n -eq $data ]]
  set +x
}

./setup
check
check
check
check
