#!/bin/bash
set -o errexit -o nounset -o pipefail

function query {
  ./run bash -c '
    set -o errexit -o nounset -o pipefail
    url="$(< "$1")" ; shift
    exec "$0" "$url" "$@"
  ' psql {db.txt} -XqAt -c "SELECT $1"
}

./setup

n="$RANDOM"
data="$(query "$n")"

set -x
[[ $n -eq $data ]]
set +x
