#!/bin/bash
set -o errexit -o nounset -o pipefail
function usage {
cat <<USAGE
 USAGE: ...database-path.../remove

  Delete the database directory. Stops the server first, if it happens to be
  running.

USAGE
}

function remove {
  ./stop -m immediate -w
  rm -rf "$self"
}

source "$(dirname "${BASH_SOURCE[0]}")"/main
main "$@"
