#!/bin/bash
set -o errexit -o nounset -o pipefail
function usage {
cat <<USAGE
 USAGE: ...database-path.../stop <pg_ctl-arguments>*

  Stop the database server, if running. Any arguments are passed directly to
  \`pg_ctl\`. For example:

    -w

  to wait for shutdown. If no arguments are passed, the default set is:

    ${default_arguments[@]}

  Postgres supports a "smart" shutdown method, with \`-m smart\`, that causes
  the server to stop only after all clients have disconnected. This can be
  useful.

USAGE
}

default_arguments=( -w -m fast --silent )

function stop {
  local code=0

  if ./status --is-running
  then
    log 'Requesting server shutdown...'
    ctl stop "${@:-${default_arguments[@]}}" >&2
  else
    log 'Server not running.'
  fi
}

source "$(dirname "${BASH_SOURCE[0]}")"/main
main "$@"
