#!/bin/bash
set -o errexit -o nounset -o pipefail
function usage {
cat <<USAGE
 USAGE: ...database-path.../stop <pg_ctl-arguments>*

  Stop the database server, if running. Any arguments are passed directly to
  \`pg_ctl\`. For example:

    -w

  to wait for shutdown. If no arguments are passed, the default set is:

    ${default_arguments[@]}

USAGE
}

default_arguments=( -w -m fast )

function stop {
  local status=
  if status="$(status)"
  then
    if fgrep -q 'server is running' <<<"$status"
    then
      log 'Shutting down server...'
      ctl stop "${@:-${default_arguments[@]}}"
    else
      log 'Server not running.'
    fi
  else
    # The if-else should not be needed to capture the error status here. The
    # `errexit` option should handle it. However, it doesn't work.
    exit $?
  fi
}

source "$(dirname "$0")"/main
main "$@"
